name: prototype2021
description: A new Flutter project.

publish_to: 'none'

version: 1.0.6+7

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  # material_floating_search_bar: ^0.2.3
  cupertino_icons: ^1.0.0
  audioplayers: ^0.20.1 
  f_datetimerangepicker: ^0.1.3
  carousel_slider: ^4.0.0 
  fluttertoast: ^8.0.8

  google_maps_flutter: ^2.0.2
  #Provider Pattern
  provider: ^5.0.0

  http: ^0.13.3

  dots_indicator: ^2.0.0

  # Search Bar 
  material_floating_search_bar: ^0.3.4

  # Current location
  geolocator: ^7.6.0
  
  image_picker: ^0.8.4

  # Geodesy
  geodesy: 0.4.0-nullsafety.0

   # Amazone S3
  simple_s3: ^0.3.2
  path_provider: ^2.0.0

   # Device Storage for simple data
  shared_preferences: ^2.0.7

  # rxdart (More functionalities related with streams)
  rxdart: ^0.27.2

  # For parsing data from API
  html: ^0.15.0

  # Launch url on the external browser
  url_launcher: ^6.0.10

  flutter_screenutil: ^5.0.0+2

  permission_handler: ^8.2.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  build_runner: ^2.1.2
  flutter_localizations:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"